text1 = "is always an exciting experience. It is a fascinating adventure. I had one such experience during the last summer vacations, when I visited Bhopal. With my family, I reached Bhopal by train. After some rest, we undertook a visit to Bhopal. Bhopal is a historical city. We visited the Sanchi Stupa first. The 'Sanchi Stupa' is located about 46 km away from Bhopal in a small place called Sanchi. Sanchi is a small village in Raisen District of the state of Madhya Pradesh, India. It is a religious place with historical and archaeological significance. It is the location of several Buddhist monuments. The place is famous for the Stupas (brick mounds) which were built on the top of a hill. The Great Stupa at Sanchi is the oldest stone structure in India. It was originally commissioned by the emperor Ashoka the Great. It has four profusely carved ornamental gateways and a balustrade encircling the whole structure. By noon, we had completed the tour of Sanchi Stupa and returned back. I enjoyed my trip to the Sanchi Stupa very much. It was really an unforgettable experience which apart from being intellectually rewarding gave us a glimpse of our country's proud history."

text2 = "A visit to a historical place a I had never seen a house on fire before, so, one evening when I heard fire engines with loud alarm bells rushing past my house. I quickly ran out and, a few streets away, joined a large crowd of people. We could see the fire only from a distance because the police would not allow any one near the building on fire. What a terrible scene I saw that day! Huge flames of fire were coming out of each floor, and black and thick smoke spread all around. Four fire engines were engaged and the firemen in their uniform were playing the hose on various parts of the building. Then the tall ladders of the fire engine were stretched upwards. Some firemen climbed up with hoses in their hands. The continuous flooding brought the fire under control but the building was completely destroyed."

text3 = "There is some truth in the common saying that while dogs become attached to the persons, cats are generally attached to the places. A dog will follow his master anywhere, but a cat keeps to the house it is used to. Even when the house changes hand, the cat will remain there, so long as it is kindly treated by the new owners.A cat does not seem to be capable of the personal devotion often shown by a dog. It thinks most of its own comfort, and its love is only cupboard love. There is some truth in the common saying that while dogs become attached to the persons, cats are generally attached to the places. A dog will follow his master anywhere, but a cat keeps to the house it is used to. Even when the house changes hand, the cat will remain there, so long as it is kindly treated by the new owners.A cat does not seem to be capable of the personal devotion often shown by a dog. It thinks most of its own comfort, and its love is only cupboard love. There is some truth in the common saying that while dogs become attached to the persons, cats are generally attached to the places. A dog will follow his master anywhere, but a cat keeps to the house it is used to. Even when the house changes hand, the cat will remain there, so long as it is kindly treated by the new owners.A cat does not seem to be capable of the personal devotion often shown by a dog. It thinks most of its own comfort, and its love is only cupboard love. There is some truth in the common saying that while dogs become attached to the persons, cats are generally attached to the places. A dog will follow his master anywhere, but a cat keeps to the house it is used to. Even when the house changes hand, the cat will remain there, so long as it is kindly treated by the new owners.A cat does not seem to be capable of the personal devotion often shown by a dog. It thinks most of its own comfort, and its love is only cupboard love. There is some truth in the common saying that while dogs become attached to the persons, cats are generally attached to the places. A dog will follow his master anywhere, but a cat keeps to the house it is used to. Even when the house changes hand, the cat will remain there, so long as it is kindly treated by the new owners.A cat does not seem to be capable of the personal devotion often shown by a dog. It thinks most of its own comfort, and its love is only cupboard love love is only cupboard love love is only cupboard love love is only cupboard love love is only cupboard love love is only cupboard love love is only cupboard love love is only cupboard love. "

text4 = "A visit to a historical place a I had never seen a house on fire before, so, one evening when I heard fire engines with loud alarm bells rushing past my house. I quickly ran out and, a few streets away, joined a large crowd of people. We could see the fire only from a distance because the police would not allow any one near the building on fire. What a terrible scene I saw that day! Huge flames of fire were coming out of each floor, and black and thick smoke spread all around. Four fire engines were engaged and the firemen in their uniform were playing the hose on various parts of the building. Then the tall ladders of the fire engine were stretched upwards. Some firemen climbed up with hoses in their hands. The continuous flooding brought the fire under control but the building was completely destroyed and."

text5 = "is always an exciting experience. It is a fascinating adventure. I had one such experience during the last summer vacations, when I visited Bhopal. With my family, I reached Bhopal by train. After some rest, we undertook a visit to Bhopal. Bhopal is a historical city. We visited the Sanchi Stupa first. The 'Sanchi Stupa' is located about 46 km away from Bhopal in a small place called Sanchi. Sanchi is a small village in Raisen District of the state of Madhya Pradesh, India. It is a religious place with historical and archaeological significance. It is the location of."

text6 = "hi"

print(len(text1.split()))
print(len(text2.split()))
print(len(text3.split()))
print(len(text4.split()))
print(len(text5.split()))